/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import client.controller.ClientController;
import client.view.models.TableModelApartmentFeatures;
import domain.ApartmentFeatures;
import domain.FeatureValue;
import domain.Listing;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author Andrej
 */
public class FrmApartmentFeatures extends javax.swing.JDialog {

    /**
     * Creates new form FrmApartmentFeatures
     */
    Listing listing;
    FrmListing frm;
    boolean flag = false;
    public FrmApartmentFeatures(FrmListing frm,Listing listing) {
        this.frm = frm;
        this.listing = listing;
        initComponents();
        setLocationRelativeTo(null);
        TableModelApartmentFeatures model = new TableModelApartmentFeatures();
        tblApartmentFeatures.setModel(model);
        fillTable();
        model.setListing(listing);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnInsertValue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApartmentFeatures = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnInsertValue.setText("Insert Value");
        btnInsertValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertValueActionPerformed(evt);
            }
        });

        tblApartmentFeatures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblApartmentFeatures);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(112, 112, 112)
                        .addComponent(btnInsertValue)
                        .addGap(124, 124, 124)
                        .addComponent(btnSubmit)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertValue)
                    .addComponent(btnCancel)
                    .addComponent(btnSubmit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnInsertValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertValueActionPerformed
        int row = tblApartmentFeatures.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati odgovarajucu karakteristiku!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        TableModelApartmentFeatures model = (TableModelApartmentFeatures) tblApartmentFeatures.getModel();
        ApartmentFeatures af = model.getApartmentFeature(row);
        FrmFeatureValues frm = new FrmFeatureValues(af, this, listing);
        frm.setVisible(true);

    }//GEN-LAST:event_btnInsertValueActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(flag==false){
            JOptionPane.showMessageDialog(this, "You must insert atleast one apartment feature value!");
            return;
        }
        frm.setListing(listing);
        this.dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsertValue;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblApartmentFeatures;
    // End of variables declaration//GEN-END:variables

    

    void addFeatureValue(Listing listing, ApartmentFeatures af, FeatureValue fv) {
        if(this.listing==null){
            System.out.println("Listing is null");
            return;
        }
        if(this.listing.getFeatureValues()==null){
            this.listing.setFeatureValues(new ArrayList<FeatureValue>());
        }
        this.listing.getFeatureValues().add(fv);
        
        if(af.getFeatureValues()==null){
            af.setFeatureValues(new ArrayList<FeatureValue>());
        }
        af.getFeatureValues().add(fv);
        TableModelApartmentFeatures model = (TableModelApartmentFeatures) tblApartmentFeatures.getModel();
        model.updateFeature(af);
        flag = true;
    }

    private void fillTable() {
     TableModelApartmentFeatures model = (TableModelApartmentFeatures) tblApartmentFeatures.getModel();
     model.fillTable();
    }
}
