/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.view.form;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import server.threads.ServerThread;

/**
 *
 * @author Andrej
 */
public class FrmServerMain extends javax.swing.JFrame {

    private ServerThread serverThread;

    /**
     * Creates new form FrmMain
     */
    public FrmServerMain() {
        initComponents();
        setLocationRelativeTo(null);
        miStopServer.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuServer = new javax.swing.JMenuBar();
        jMenuServer = new javax.swing.JMenu();
        miStartServer = new javax.swing.JMenuItem();
        miStopServer = new javax.swing.JMenuItem();
        jMenuConfig = new javax.swing.JMenu();
        miDatabaseConfig = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenuServer.setText("Server");

        miStartServer.setText("Start Server");
        miStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStartServerActionPerformed(evt);
            }
        });
        jMenuServer.add(miStartServer);

        miStopServer.setText("Stop Server");
        miStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStopServerActionPerformed(evt);
            }
        });
        jMenuServer.add(miStopServer);

        menuServer.add(jMenuServer);

        jMenuConfig.setText("Configuration");

        miDatabaseConfig.setText(" Database configuration");
        miDatabaseConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDatabaseConfigActionPerformed(evt);
            }
        });
        jMenuConfig.add(miDatabaseConfig);

        menuServer.add(jMenuConfig);

        setJMenuBar(menuServer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStartServerActionPerformed
        if (serverThread == null || !serverThread.isAlive()) {
            try {
                serverThread = new ServerThread();
                serverThread.start();
                miStartServer.setEnabled(false);
                miStopServer.setEnabled(true);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_miStartServerActionPerformed

    private void miStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStopServerActionPerformed
        if(serverThread!=null && serverThread.getServerSocket().isBound()){
            try {
                serverThread.getServerSocket().close();
                 miStartServer.setEnabled(true);
                miStopServer.setEnabled(false);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_miStopServerActionPerformed

    private void miDatabaseConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDatabaseConfigActionPerformed
     FrmDatabaseConfiguration frm = new FrmDatabaseConfiguration(this, rootPaneCheckingEnabled);
     frm.setVisible(true);
    }//GEN-LAST:event_miDatabaseConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuConfig;
    private javax.swing.JMenu jMenuServer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuServer;
    private javax.swing.JMenuItem miDatabaseConfig;
    private javax.swing.JMenuItem miStartServer;
    private javax.swing.JMenuItem miStopServer;
    // End of variables declaration//GEN-END:variables
}
