/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author Andrej
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuMain = new javax.swing.JMenuBar();
        jMenuEmployee = new javax.swing.JMenu();
        miAddEmployee = new javax.swing.JMenuItem();
        miEditEmployee = new javax.swing.JMenuItem();
        miDeleteEmployee = new javax.swing.JMenuItem();
        jMenuListing = new javax.swing.JMenu();
        miAddListing = new javax.swing.JMenuItem();
        miSearchListings = new javax.swing.JMenuItem();
        miEditListing = new javax.swing.JMenuItem();
        miDeleteListing = new javax.swing.JMenuItem();
        jMenuRental = new javax.swing.JMenu();
        miAddRental = new javax.swing.JMenuItem();
        miSearchRental = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        jMenuEmployee.setText("Employee");

        miAddEmployee.setText("Add Employee");
        jMenuEmployee.add(miAddEmployee);

        miEditEmployee.setText("Edit Employee");
        jMenuEmployee.add(miEditEmployee);

        miDeleteEmployee.setText("Delete Employee");
        jMenuEmployee.add(miDeleteEmployee);

        jMenuMain.add(jMenuEmployee);

        jMenuListing.setText("Listing");

        miAddListing.setText("Add Listing");
        jMenuListing.add(miAddListing);

        miSearchListings.setText("Search Listings");
        jMenuListing.add(miSearchListings);

        miEditListing.setText("Edit Listing");
        jMenuListing.add(miEditListing);

        miDeleteListing.setText("Delete Listing");
        jMenuListing.add(miDeleteListing);

        jMenuMain.add(jMenuListing);

        jMenuRental.setText("Rental");

        miAddRental.setText("Add Rental");
        jMenuRental.add(miAddRental);

        miSearchRental.setText("Search Rentals");
        jMenuRental.add(miSearchRental);

        jMenuMain.add(jMenuRental);

        setJMenuBar(jMenuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuEmployee;
    private javax.swing.JMenu jMenuListing;
    private javax.swing.JMenuBar jMenuMain;
    private javax.swing.JMenu jMenuRental;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miAddEmployee;
    private javax.swing.JMenuItem miAddListing;
    private javax.swing.JMenuItem miAddRental;
    private javax.swing.JMenuItem miDeleteEmployee;
    private javax.swing.JMenuItem miDeleteListing;
    private javax.swing.JMenuItem miEditEmployee;
    private javax.swing.JMenuItem miEditListing;
    private javax.swing.JMenuItem miSearchListings;
    private javax.swing.JMenuItem miSearchRental;
    // End of variables declaration//GEN-END:variables
}
